# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-11-21 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20171119_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='name',
            field=models.CharField(max_length=100, verbose_name='\u7ae0\u8282\u540d'),
        ),
    ]
