# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2019-03-23 22:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_auto_20171208_2151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseresource',
            name='course',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='course',
        ),
        migrations.RemoveField(
            model_name='video',
            name='lesson',
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': '识别模型', 'verbose_name_plural': '识别模型'},
        ),
        migrations.DeleteModel(
            name='CourseResource',
        ),
        migrations.DeleteModel(
            name='Lesson',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
