# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2019-03-27 14:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_auto_20190323_2232'),
    ]

    operations = [
        migrations.CreateModel(
            name='activityID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='1', max_length=10, verbose_name='运动类别')),
            ],
            options={
                'verbose_name': '运动种类',
                'verbose_name_plural': '运动种类',
            },
        ),
        migrations.AlterField(
            model_name='course',
            name='course_org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.CourseOrg', verbose_name='模型名称'),
        ),
    ]
