# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2019-03-27 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_auto_20190327_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityid',
            name='name',
            field=models.CharField(max_length=20, verbose_name='运动类别'),
        ),
    ]
