# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2019-03-27 15:36
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0013_auto_20190327_1504'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='课程名')),
                ('add_time', models.DateTimeField(verbose_name='添加时间')),
                ('download', models.FileField(upload_to='course/resource/%Y/%m', verbose_name='资源信息')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course', verbose_name='课程')),
            ],
            options={
                'verbose_name_plural': '课程资源',
                'verbose_name': '课程资源',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='章节名')),
                ('add_time', models.DateTimeField(verbose_name='添加时间')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course', verbose_name='课程')),
            ],
            options={
                'verbose_name_plural': '课程章节',
                'verbose_name': '课程章节',
            },
        ),
        migrations.CreateModel(
            name='SportData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('rate', models.IntegerField(blank=True, null=True, verbose_name='心率')),
                ('position', models.IntegerField(default=0, verbose_name='传感器位置')),
                ('type', models.IntegerField(default=0, verbose_name='传感器种类 ')),
                ('data_x', models.FloatField(verbose_name='传感器x轴数据')),
                ('data_y', models.FloatField(verbose_name='传感器y轴数据')),
                ('data_z', models.FloatField(verbose_name='传感器z轴数据')),
                ('sportid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.activityID', verbose_name='运动类别')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name_plural': '运动数据',
                'verbose_name': '运动数据',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='视频名')),
                ('add_time', models.DateTimeField(verbose_name='添加时间')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Lesson', verbose_name='章节')),
            ],
            options={
                'verbose_name_plural': '课程视频',
                'verbose_name': '课程视频',
            },
        ),
    ]
