# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-11-22 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0002_auto_20171121_1705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfavorite',
            name='course',
        ),
        migrations.RemoveField(
            model_name='userfavorite',
            name='teacher',
        ),
        migrations.AlterField(
            model_name='userfavorite',
            name='fav_type',
            field=models.IntegerField(choices=[(1, '\u8bfe\u7a0b'), (2, '\u673a\u6784'), (3, '\u6559\u7ec3')], verbose_name='\u6536\u85cf\u7c7b\u578b'),
        ),
    ]
