# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-11-24 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20171113_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='birday',
            field=models.DateField(blank=True, default='2010-01-01', null=True, verbose_name='\u751f\u65e5'),
        ),
    ]
