# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-11-24 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20171124_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='birthday',
            field=models.DateField(blank=True, default='2010-01-01', null=True, verbose_name='\u751f\u65e5'),
        ),
    ]
