# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2019-03-23 22:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20171209_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='height',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='身高'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='weight',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='体重'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
    ]
