# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-11-29 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_courseorg_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseorg',
            name='catgory',
        ),
        migrations.AddField(
            model_name='courseorg',
            name='category',
            field=models.CharField(choices=[('pxjg', '\u57f9\u8bad\u5c31\u591f'), ('gx', '\u9ad8\u6821'), ('gr', '\u4e2a\u4eba')], default='gx', max_length=20, verbose_name='\u673a\u6784\u7c7b\u522b'),
        ),
    ]
