# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-11-29 18:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_auto_20171129_1820'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseorg',
            old_name='category',
            new_name='catgory',
        ),
    ]
