# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2019-03-27 14:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0009_remove_courseorg_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseorg',
            options={'verbose_name': '模型列表', 'verbose_name_plural': '模型列表'},
        ),
    ]
